export const INIT_GET_NOTES = "INIT_GET_NOTES";
export const FETCHING_NOTES_SUCCESS = "FETCHING_NOTES_SUCCESS";
export const FETCHING_NOTES_FAILED = "FETCHING_NOTES_FAILED";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_ALL_NOTES = "DELETE_ALL_NOTES";
